# Generated by Django 2.2.7 on 2020-10-15 01:18

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('image', stdimage.models.StdImageField(upload_to='media/', verbose_name='Imagem')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
            ],
            options={
                'verbose_name': 'Galeria de Foto',
                'verbose_name_plural': 'Galeria de Fotos',
            },
        ),
    ]
