# Generated by Django 2.2.7 on 2020-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryphoto',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aprovado'),
        ),
    ]
