# Generated by Django 2.2.7 on 2020-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201015_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryphoto',
            name='approved',
            field=models.BooleanField(default=False, null=True, verbose_name='Aprovado'),
        ),
    ]
