# Generated by Django 2.2.7 on 2020-10-15 19:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201015_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryphoto',
            name='image',
            field=stdimage.models.StdImageField(upload_to='', verbose_name='Imagem'),
        ),
    ]
