# Generated by Django 2.2.7 on 2020-10-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201015_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryphoto',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
