# Generated by Django 2.2.7 on 2020-10-16 00:13

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201015_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryphoto',
            name='image',
            field=stdimage.models.StdImageField(upload_to='media/', verbose_name='Imagem'),
        ),
    ]
