# Generated by Django 2.2.7 on 2020-10-16 00:15

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201015_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryphoto',
            name='image',
            field=stdimage.models.StdImageField(upload_to='', verbose_name='Imagem'),
        ),
    ]
